name: flutter_app
description: A new Flutter application.

publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  event: ^2.0.5
  flutter:
    sdk: flutter
  flutter_native_splash: ^1.2.3
  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.4
  carousel_slider: ^4.0.0
  http: ^0.13.3
  tmdb_api: 2.0.0-nullsafety
  json_serializable: 4.1.4
  json_annotation: 4.0.1
  build_runner: 2.1.1
  convert: 3.0.1
  url_launcher: 6.0.9
  cached_network_image: 3.1.0
  shared_preferences: 2.0.7
  dio: 4.0.0
  intl: 0.17.0
  bloc: 7.1.0
  youtube_player_flutter: ^8.0.0
  youtube_player_iframe: ^2.2.2
  flutter_launcher_icons: ^0.9.2
  get_it: ^7.2.0
  share_plus: 2.1.4
  flutter_bloc: 7.2.0
  flutter_locales: 2.0.0
  google_mobile_ads: ^0.13.4
  moviego_models:
    path: packages/moviego_models
  moviego_repositories:
    path: packages/moviego_repositories


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/category/
    - assets/locales/

flutter_icons:
  image_path: "assets/images/icon.png"
  image_path_android: "assets/images/android/icon.png"
  #image_path_ios: "assets/images/android/icon.png"
  android: true
  ios: true

flutter_native_splash:
  color: '#ffffff'
  image: 'assets/images/splash.png'
  android: true
  ios: true
