name: moviego_repositories
description: A new Flutter application.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hexcolor: ^2.0.4
  carousel_slider: ^4.0.0
  http: ^0.13.3
  tmdb_api: 2.0.0-nullsafety
  json_serializable: 4.1.4
  json_annotation: 4.0.1
  build_runner: 2.1.1
  convert: 3.0.1
  dio: 4.0.0
  moviego_models:
    path: ../moviego_models
  moviego_services:
    path: ../moviego_services
  event: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
   